### ISSUE TITLE
Youtube images aren't showing up on ReadMe

### ISSUE THREAD

**Issue by zombodotcom** [michalin/Blu-ray-Laser-Scanning-Microscope#1]
![image](https://user-images.githubusercontent.com/13477955/218273934-e11f491d-1a5d-41b2-9652-77cd0f54fb44.png)

this should fix it if you copy the markdown. 

---
## Watch Videos to Learn More
In Part 1 you will see how I re-engineered an optical pickup unit from a broken Blu-ray player so that it can be used for a laser scanning microscope.

<a href="https://youtu.be/liGuhbFh4IQ" alt="DIY Blu-Ray Laser Scanning Microscope #1: Making a Laser Microphone">
<img width="560" height="315" src="https://i3.ytimg.com/vi/liGuhbFh4IQ/maxresdefault.jpg"></img>
</a>

---
Part 2 is about a working prototype that builds on the existing CD/DVD/Blu-ray drive I salvaged from the Blu-ray player.

<a href="https://youtu.be/Hkialty_8K4" alt="DIY Blu-Ray Laser Scanning Microscope #2: Shooting Images">
<img width="560" height="315" src="https://i3.ytimg.com/vi/Hkialty_8K4/maxresdefault.jpg"></img>
</a>

---
Part 3 shows how to build an improved version of the microscope from 3D printed parts and how to use it.  

<a href="https://youtu.be/xfuWbnMYOos" alt="DIY Blu-Ray Laser Scanning Microscope #3: Improvements And Tests">
<img width="560" height="315" src="https://i3.ytimg.com/vi/xfuWbnMYOos/maxresdefault.jpg"></img>
</a>

**Comment by michalin** [comment]
Thank you. I fixed it.
